version: "3.7"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: uchinoko_project
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
